# Generated by Django 4.1.4 on 2023-01-04 16:36

import Seller_central.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_Name', models.CharField(max_length=255)),
                ('user_email_phone', models.EmailField(max_length=255)),
                ('user_Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_ID', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('vendor_Name', models.CharField(max_length=255)),
                ('vendor_Password', models.CharField(max_length=255)),
                ('vendor_CNIC', models.CharField(max_length=255)),
                ('vendor_Type', models.CharField(max_length=255)),
                ('vendor_Phone', models.IntegerField(max_length=100)),
                ('vendor_Bank_Details', djongo.models.fields.EmbeddedField(model_container=Seller_central.models.Vendor_Bank_Details)),
                ('user_ID', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='Seller_central.user')),
            ],
        ),
    ]
